"""
Short Go agent — full orchestration to queue one post to Make.com → Buffer.

The agent's per-post pipeline:

    1. PostPlan dataclass holds: background + post_type + copy + caption + schedule
    2. prepare_post(plan) renders the PNG (via compose_post), stages it into the
       GitHub assets repo (via image_host), and returns a "ready-to-push" payload
       including the git push command and the Make webhook payload.
    3. The agent then runs the git push via osascript on Charles's Mac.
    4. fire_webhook() POSTs the prepared payload to the Make webhook.

This module is intentionally separated into prepare → push → fire so each step is
testable in isolation. The git push lives outside Python because GitHub creds
live on Charles's Mac, not in the Cowork sandbox.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

# Local imports
_LIB = Path(__file__).resolve().parent
sys.path.insert(0, str(_LIB))

from compose_post import compose_post, PostSpec
from image_host import stage_and_return_url, repo_root, build_key, stage_image, raw_url_for_key
from feed_preview import render_feed_preview

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

PHOTO_LIBRARY = _LIB.parent / "photo-library"
RENDER_OUTPUT_DIR = _LIB.parent / "_renders"   # rendered PNGs land here before staging

# Where the Make webhook URL is stored (Charles's Mac, chmod 600)
DEFAULT_WEBHOOK_PATH = Path.home() / ".config/short-go-agent/make-webhook-url"


# ---------------------------------------------------------------------------
# Plan dataclass
# ---------------------------------------------------------------------------

@dataclass
class PostPlan:
    """One week-of post: copy + chosen background + schedule.

    Generated by the Sunday agent. Consumed by prepare_post().
    """
    post_id: str
    post_type: Literal["educational", "cta", "quote"]
    background_filename: str        # must exist in PHOTO_LIBRARY (e.g. "008-barn-aisle-light-beam.png")
    hook: list[str]                 # 1–3 lines, all uppercase for editorial templates
    body: list[str] = field(default_factory=list)
    explainer: str | None = None
    caption: str = ""               # IG/FB post body text (separate from image overlay)
    scheduled_at: str = ""          # ISO datetime: "2026-05-20T14:00:00Z"
    channels: list[str] = field(default_factory=lambda: ["instagram", "facebook"])


# ---------------------------------------------------------------------------
# Step 1 — Render + stage
# ---------------------------------------------------------------------------

def prepare_post(plan: PostPlan) -> dict:
    """
    Render the post + stage the PNG into the assets repo + build the webhook
    payload. Does NOT push to git or fire the webhook — caller does those.

    Returns a dict with:
        rendered_png:        local sandbox path of the freshly-rendered PNG
        staged_repo_path:    where it now sits inside the local assets repo clone
        public_url:          raw.githubusercontent.com URL (valid after push)
        git_push_command:    shell command to run via osascript on Charles's Mac
        webhook_payload:     ready-to-POST JSON for the Make webhook
    """
    # 1. Validate the background exists
    bg = PHOTO_LIBRARY / plan.background_filename
    if not bg.exists():
        raise FileNotFoundError(f"Background not in photo-library: {plan.background_filename}")

    # 2. Render the PNG
    RENDER_OUTPUT_DIR.mkdir(exist_ok=True)
    render_path = RENDER_OUTPUT_DIR / f"{plan.post_id}.png"
    spec = PostSpec(
        background_path=bg,
        template=plan.post_type,
        hook=plan.hook,
        body=plan.body,
        explainer=plan.explainer,
    )
    compose_post(spec, render_path)

    # 3a. Stage the post image into the assets repo at posts/YYYY-MM-DD/{post_id}.png
    staged = stage_and_return_url(
        local_png_path=render_path,
        post_id=plan.post_id,
        scheduled_at=plan.scheduled_at,
    )

    # 3b. Render the IG feed-preview mockup (approval-only — not what IG receives)
    preview_render_path = RENDER_OUTPUT_DIR / f"{plan.post_id}.preview.png"
    render_feed_preview(
        rendered_post_path=render_path,
        caption=plan.caption,
        output_path=preview_render_path,
    )

    # 3c. Stage the preview under previews/YYYY-MM-DD/ so it gets its own raw URL.
    #     stage_image() builds the path directly; we then construct the URL.
    preview_key = build_key(plan.post_id, plan.scheduled_at).replace(
        "posts/", "previews/", 1
    ).replace(".png", ".preview.png")
    stage_image(preview_render_path, preview_key)
    preview_public_url = raw_url_for_key(preview_key)

    # 4. Build the webhook payload matching the Make scenario's expected schema
    payload = {
        "post_id":      plan.post_id,
        "post_type":    plan.post_type,
        "image_url":    staged["public_url"],
        "caption":      plan.caption,
        "schedule_at":  plan.scheduled_at,
        "channel":      ",".join(plan.channels),
        "hook":         " ".join(plan.hook),
        "subhead_1":    plan.body[0] if len(plan.body) > 0 else "",
        "subhead_2":    plan.body[1] if len(plan.body) > 1 else "",
        "subhead_3":    plan.body[2] if len(plan.body) > 2 else "",
        "explainer":    plan.explainer or "",
        "test":         False,
    }

    return {
        "post_id":            plan.post_id,
        "rendered_png":       str(render_path),
        "preview_png":        str(preview_render_path),
        "staged_repo_path":   staged["repo_path"],
        "key":                staged["key"],
        "public_url":         staged["public_url"],
        "preview_key":        preview_key,
        "preview_url":        preview_public_url,
        "git_push_command":   staged["git_commit_command"],
        "webhook_payload":    payload,
    }


# ---------------------------------------------------------------------------
# Step 3 — Fire the Make webhook
# ---------------------------------------------------------------------------

def _load_webhook_url(path: Path = DEFAULT_WEBHOOK_PATH) -> str:
    if not path.exists():
        raise FileNotFoundError(
            f"Webhook URL not found at {path}. "
            "Charles needs to save the Make webhook URL there."
        )
    url = path.read_text().strip()
    if not url.startswith("https://hook."):
        raise ValueError(f"Webhook URL doesn't look right: {url!r}")
    return url


def fire_webhook(payload: dict, webhook_url: str | None = None, timeout: int = 15) -> dict:
    """POST the prepared payload to the Make webhook. Returns response status + body.

    Caller should only call this AFTER the git push has succeeded — otherwise
    the public_url in the payload won't yet serve the image and Buffer will fail
    to attach media.
    """
    if webhook_url is None:
        webhook_url = _load_webhook_url()

    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        webhook_url,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return {
                "status": resp.status,
                "body": resp.read().decode("utf-8", errors="replace"),
                "ok": 200 <= resp.status < 300,
            }
    except urllib.error.HTTPError as e:
        return {
            "status": e.code,
            "body": e.read().decode("utf-8", errors="replace"),
            "ok": False,
        }
    except urllib.error.URLError as e:
        return {"status": None, "body": f"URLError: {e.reason}", "ok": False}


# ---------------------------------------------------------------------------
# CLI for manual end-to-end testing
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    """
    Manual test driver. Usage:
        python queue_to_make.py prepare path/to/plan.json
        python queue_to_make.py fire path/to/payload.json
    """
    if len(sys.argv) < 3:
        print(
            "Usage:\n"
            "  python queue_to_make.py prepare <plan.json>\n"
            "  python queue_to_make.py fire    <payload.json>",
            file=sys.stderr,
        )
        sys.exit(2)

    cmd, src = sys.argv[1], Path(sys.argv[2])
    data = json.loads(src.read_text())

    if cmd == "prepare":
        plan = PostPlan(**data)
        result = prepare_post(plan)
        # Strip the raw payload so the prepare output is human-readable;
        # caller saves it to fire later.
        out_payload_path = src.with_name(src.stem + ".payload.json")
        out_payload_path.write_text(json.dumps(result["webhook_payload"], indent=2))
        result["webhook_payload_saved_to"] = str(out_payload_path)
        del result["webhook_payload"]
        print(json.dumps(result, indent=2))
    elif cmd == "fire":
        resp = fire_webhook(data)
        print(json.dumps(resp, indent=2))
        sys.exit(0 if resp["ok"] else 1)
    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        sys.exit(2)
